#define MOUSEKEY_DELAY 10
#define MOUSEKEY_TIME_TO_MAX 20
#define MOUSEKEY_MAX_SPEED 20
#define MOUSEKEY_WHEEL_DELAY 10

#define USB_MAX_POWER_CONSUMPTION 100

#define TAPPING_TERM 150
#define IGNORE_MOD_TAP_INTERRUPT
/* #define RGB_DISABLE_WHEN_USB_SUSPENDED */
/* #define LEADER_TIMEOUT 300 */
/* #define COMBO_COUNT 4 */

